{
 "title": "OrangePi monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Birds", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Bird Counts",
   "type": "heatmap",
   "gridPos": { "h": 16, "w": 22, "x": 0, "y": 1 },
   "targets": [
    { "expr": "bird_species_count", "legendFormat": "{{species}}" }
   ]
  },
  {
   "title": "Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true
  },
  {
   "title": "Storage Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{mountpoint=~\"/|/bird-detections\"}-node_filesystem_free_bytes{mountpoint=~\"/|/bird-detections\"})/node_filesystem_size_bytes{mountpoint=~\"/|/bird-detections\"}*100",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "IO Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "MiBs" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"mmcblk1|sda\"}[5m])/1024/1024",
     "legendFormat": "Read {{device}}"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"mmcblk1|sda\"}[5m])/1024/1024",
     "legendFormat": "Write {{device}}"
    }
   ]
  },
  { "title": "Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (cpu))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "rknpu_core_load_percentage", "legendFormat": "{{core}}" }
   ]
  }
 ]
}