services:
  rtmp-server:
    image: ${NGINX_RTMP_DOCKER_IMG}
    container_name: rtmp-server-container
  stream:
    depends_on: 
      - rtmp-server
    image: ${FFMPEG_DOCKER_IMG}
    container_name: ffmpeg-streamer
    devices:
      - /dev/video${VIDEO_IDX}:/dev/video0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: ffmpeg -thread_queue_size 1600 -f v4l2 -input_format mjpeg -video_size 1920x1080 -i /dev/video0 -f lavfi -i anullsrc -g 60 -c:v h264_nvenc -preset slow -b:v 6800K -maxrate 6800K -f flv rtmp://rtmp-server/live/birbs
  push:
    depends_on:
      - stream
      - rtmp-server
    image: ${FFMPEG_DOCKER_IMG}
    container_name: ffmpeg-pusher
    command: ffmpeg -i rtmp://rtmp-server/live/birbs -c copy -f flv rtmp://a.rtmp.youtube.com/live2/${YT_LIVE_KEY}
  detect:
    depends_on:
      - stream
      - rtmp-server
    image: ${YOLO_DOCKER_IMG}
    container_name: birb-detector
    command: python capture.py -l rtmp://rtmp-server/live/birbs
    volumes:
      - .:/tmp/birds
      - /etc/localtime:/etc/localtime:ro
    working_dir: /tmp/birds
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
