services:
  detect:
    image: ${YOLO_DOCKER_IMG}
    container_name: birb-detector
    command: python capture.py -l 0 -d ${YOLO_DETECTOR_MODEL} -c ${YOLO_CLASSIFIER_MODEL}
    volumes:
      - .:/tmp/birds
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/video${VIDEO_IDX}:/dev/video0
    working_dir: /tmp/birds
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
