services:
  node_exporter:
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    command: 
      - '--path.rootfs=/host'
      - '--web.listen-address=:9091'
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    ports:
      - '9091:9091'
    cpuset: 0-1
    networks:
      - bird_net

  rknpu_exporter:
    image: ${BIRDS_CONTAINER}
    container_name: rknpu_exporter
    working_dir: /app
    volumes:
      - /sys/kernel/debug/rknpu/load:/rknpu-load.txt:ro
    entrypoint: rknpu-exporter
    restart: unless-stopped
    cpuset: 0-1
    networks:
      - bird_net
  
  init_prometheus:
    image: quay.io/prometheus/prometheus
    user: root
    entrypoint:
      - /bin/sh
      - -c
      - |
        chown -R 65534:65534 /prometheus
    volumes:
      - /bird-detections/prometheus-data:/prometheus
  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - /bird-detections/prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - node_exporter
      - rknpu_exporter
      - init_prometheus 
    restart: unless-stopped
    networks:
      - bird_net

  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - /bird-detections/grafana-data:/var/lib/grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    user: '0'
    cpuset: 0-1
    networks:
      - bird_net
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
  renderer:
    image: grafana/grafana-image-renderer
    ports:
      - 8081
    networks:
      - bird_net

  video0_extract:
    image: ${BIRDS_CONTAINER}
    container_name: video0-extract
    volumes:
      - /bird-detections:/output
      - /etc/localtime:/etc/localtime:ro
      - ./models/yolov5-birbs.rknn:/app/models/yolov5-birbs.rknn
      - ./models/anchors.txt:/app/models/anchors.txt
    restart: unless-stopped
    devices:
      - /dev/video0
    privileged: true
    security_opt: 
      - systempaths=unconfined
    command:
      - "/dev/video0"
      - "0"
      - "video0-"
      - "9093"
    cpuset: 2-7
    networks:
      - bird_net
  
  video2_extract:
    image: ${BIRDS_CONTAINER}
    container_name: video2-extract
    volumes:
      - /bird-detections:/output
      - /etc/localtime:/etc/localtime:ro
      - ./models/yolov5-birbs.rknn:/app/models/yolov5-birbs.rknn
      - ./models/anchors.txt:/app/models/anchors.txt
    restart: unless-stopped
    devices:
      - /dev/video2
    privileged: true
    security_opt: 
      - systempaths=unconfined
    command:
      - "/dev/video2"
      - "0"
      - "video2-"
      - "9094"
    cpuset: 2-7
    networks:
      - bird_net

networks:
  bird_net:
