services:
  video0_extract:
    image: ghcr.io/edoyango/birds
    container_name: video0-extract
    volumes:
      - /bird-detections:/output
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    devices:
      - /dev/video0
    privileged: true
    security_opt: 
      - systempaths=unconfined
    command:
      - "/dev/video0"
      - "0"
      - "video0-"
  
  video2_extract:
    image: ghcr.io/edoyango/birds
    container_name: video2-extract
    volumes:
      - /bird-detections:/output
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    devices:
      - /dev/video2
    privileged: true
    security_opt: 
      - systempaths=unconfined
    command:
      - "/dev/video2"
      - "0"
      - "video2-"
    